name: example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_flavor:
    path: "../../flutter_flavor"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_flavor:
  dimensions:
    android: "flutter-flavor"
    ios: "flutter-flavor"

  flavors:
    apple:
      app:
        name: "Apple App"
        id: "com.example.apple"
      android:
        name: "Apple App"
        applicationId: "com.example.apple"
        googleAdsId: "ca-app-pub-2647501935956905~7733581172"
        firebase: ""
      ios:
        name: "Apple App"
        bundleId: "com.example.apple"
        googleAdsId: "ca-app-pub-2647501935956905~7733581172"
        firebase: ""

    bannana:
      app:
        name: "Bannana App"
        id: "com.example.bannana"
      android:
        googleAdsId: "ca-app-pub-2647501935956905~7733581172"
        firebase: ""
      ios:
        googleAdsId: "ca-app-pub-2647501935956905~7733581172"
        firebase: ""

