name: flutter_flavor
description: "flutter_favor allows you to quickly configure and define dynamic variables for each flavor in your project. The flavors, as well as their names; they are dynamically defined by the developer or development team. In the configuration of a flavor you can set the name of each flavor, as well as the color of its banner, its location, as well as its visibility to show or hide the banner."
version: 1.1.0
homepage: https://github.com/lrferreiro/flutter_flavor

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
